### ISSUE TITLE
Syntax Error, dunno.

### ISSUE THREAD

**Issue by Alvargon75** [connec/yaml-js#18]
When I load my yaml file, it throws malformed
![screenshot_7](https://cloud.githubusercontent.com/assets/13175116/10892751/85997ba2-81a5-11e5-9149-f23f01929939.png)
![screenshot_9](https://cloud.githubusercontent.com/assets/13175116/10892877/0f4b2602-81a6-11e5-8bb7-fb143fccb543.png)

but when I log the object, it seems to be correct.
![screenshot_8](https://cloud.githubusercontent.com/assets/13175116/10892814/caa67cae-81a5-11e5-9d0a-ce4ec6321eba.png)

I don't know if this a fault in my code, just letting you know.

Also, I would like to thank you a lot you saved me hours of work.

**Comment by connec** [comment]
Hi,

This looks a lot like it comes from your code, "mal formado" is not an error this library will ever emit.

Just in case, though: what is the content of the YAML file you are trying to load?

**Comment by Alvargon75** [comment]
```yaml
# ██╗   ██╗███╗   ███╗██╗         ██████╗  ██████╗  ██████╗
# ╚██╗ ██╔╝████╗ ████║██║         ██╔══██╗██╔═══██╗██╔════╝
#  ╚████╔╝ ██╔████╔██║██║         ██║  ██║██║   ██║██║
#   ╚██╔╝  ██║╚██╔╝██║██║         ██║  ██║██║   ██║██║
#    ██║   ██║ ╚═╝ ██║███████╗    ██████╔╝╚██████╔╝╚██████╗
#    ╚═╝   ╚═╝     ╚═╝╚══════╝    ╚═════╝  ╚═════╝  ╚═════╝
# ESPAÑOL
# Esto es un fichero de configuración. Cada entrada esta documentada.
# Se usa unos indicadores con @ (estilo Javadoc) que son:
#  - @value        Los posibles valores.
#  - @deprecating  Esta propiedad dejara de usarse.
#
# ENGLISH
# This is a configuration file, each entry is documented.
# Some indicators (Javadoc style) are used. They are:
#  - @value        The possible values.
#  - @deprecating  This property won't be used.
#
#     ██╗██╗   ██╗███╗   ███╗██╗         ██████╗  ██████╗  ██████╗
#    ██╔╝╚██╗ ██╔╝████╗ ████║██║         ██╔══██╗██╔═══██╗██╔════╝
#   ██╔╝  ╚████╔╝ ██╔████╔██║██║         ██║  ██║██║   ██║██║
#  ██╔╝    ╚██╔╝  ██║╚██╔╝██║██║         ██║  ██║██║   ██║██║
# ██╔╝      ██║   ██║ ╚═╝ ██║███████╗    ██████╔╝╚██████╔╝╚██████╗
# ╚═╝       ╚═╝   ╚═╝     ╚═╝╚══════╝    ╚═════╝  ╚═════╝  ╚═════╝

# ESPAÑOL
# Salta las animaciones y hace las cosas más rápidas y menos bonitas.
# Recomendado sólo para desarrolladores.
#
# ENGLISH
# Skips animations.
# Recommended for Devs.
devMode: false

# ESPAÑOL
# Especifíca el lenguaje del juego.
# @value detect         Detecta el lenguaje de tu navegador y lo usa.
# @value códigodeidioma Código de País del Tipo es-ES, en-US
#
# ENGLISH
# Specifies the game's language.
# @value detect        Detects the language
# @value languagecode  Enter a valid language code like es-ES and en-US
language: detect

```

This is the file.
