### ISSUE TITLE
dump produces malformed yaml?

### ISSUE THREAD

**Issue by lolmaus** [connec/yaml-js#21]
```js
yaml.dump({
  attributes: {
    image-url: "http://www.2do2go.ru/uploads/full/a99dca2d765bb9c034ea8fbf315a48b2_w960_h2048.jpg",
    position: 6
  }
})
```

Expected output:

```yaml
---
attributes:
  image-url: "http://www.2do2go.ru/uploads/full/a99dca2d765bb9c034ea8fbf315a48b2_w960_h2048.jpg"
  position: 6
```

Actual output:

```yaml
attributes: {image-url: 'http://www.2do2go.ru/uploads/full/a99dca2d765bb9c034ea8fbf315a48b2_w960_h2048.jpg',
  position: 6}
```

When I try to run actual output in http://codebeautify.org/yaml-validator , it reports:

```
Error : Malformed inline YAML string "{image-url: 'http://www.2do2go.ru/uploads/full/a99dca2d765bb9c034ea8fbf315a48b2_w960_h2048.jpg'," at line 1 (near "attributes: {image-url: 'http://www.2do2go.ru/uploads/full/a99dca2d765bb9c034ea8fbf315a48b2_w960_h2048.jpg',")
Line : 1  attributes: {image-url: 'http://www.2do2go.ru/uploads/full/a99dca2d765bb9c034ea8fbf315a48b2_w960_h2048.jpg',
```
