### ISSUE TITLE
Accepting @-symbols

### ISSUE THREAD

**Issue by PatrickHeneise** [connec/yaml-js#22]
I'm trying to use Schema.org conform data in a markdown front matter. 

```
---
  @context: "http://schema.org"
  @type: "Social event"
  location: 
    @type: "Place"
    address: 
      @type: "PostalAddress"
      addressLocality: "Barcelona, Spain"
      postalCode: "08001"
      streetAddress: "C/ Fontanella 2"
    name: "Mobile World Centre"
```

the @-signs are breaking with `found character @ that cannot start any token`. There's nothing in YML 1.2 spec that doesn't allow @ characters. Any chance to get this working?

**Comment by connec** [comment]
Unfortunately this is a YAML 1.1 parser, which [disallows indicators as the first character of plain scalars](http://yaml.org/spec/1.1/#id907776).

I'm not sure what would be involved in updating the library to YAML 1.2, I'll try and investigate soon.

**Comment by connec** [comment]
Actually, it looks like [YAML 1.2 has the same restriction](http://www.yaml.org/spec/1.2/spec.html#id2788979)...

**Comment by connec** [comment]
You can of course make that document compliant by surrounding the `@` keys with quotes:

```yaml
---
  "@context": "http://schema.org"
  "@type": "Social event"
  location: 
    "@type": "Place"
    address: 
      "@type": "PostalAddress"
      addressLocality: "Barcelona, Spain"
      postalCode: "08001"
      streetAddress: "C/ Fontanella 2"
    name: "Mobile World Centre"
```
