### ISSUE TITLE
Improve default dump style

### ISSUE THREAD

**Issue by connec** [connec/yaml-js#25]
Dumping, as implemented in PyYAML, does not produce very desirable output.  Ideally the output should look like somebody wrote it.

Bad examples:
- Using flow style for (visually) large objects (#21)
  
  ``` js
  attributes: {
    'image-url': 'http://www.2do2go.ru/uploads/full/a99dca2d765bb9c034ea8fbf315a48b2_w960_h2048.jpg',
    position:    6
  }
  ```
  
  Actual
  
  ``` yaml
  attributes: {image-url: 'http://www.2do2go.ru/uploads/full/a99dca2d765bb9c034ea8fbf315a48b2_w960_h2048.jpg',
    position: 6}
  ```
  
  Expected
  
  ``` yaml
  attributes:
    image-url: http://www.2do2go.ru/uploads/full/a99dca2d765bb9c034ea8fbf315a48b2_w960_h2048.jpg
    position:  6
  ```
- Adding unecessary document end tokens to simple documents (#23)
  
  ``` js
  'foobar'
  ```
  
  Actual
  
  ``` yaml
  foobar
  ...
  ```
  
  Expected
  
  ``` yaml
  foobar
  ```
