### ISSUE TITLE
How to add a field with variables in yaml using yaml-js ?

### ISSUE THREAD

**Issue by sourcevault** [connec/yaml-js#47]
I am quite new to using `yaml-js`.

I have a field :

```yaml
var:
  file: dist/main.js
```

that I would like to merge/add to another yaml file that may look like this :

```yaml
var:
  file: &file
    dist/main.js
foo:
  - vitamin D
bar: *file
```

or just :

```yaml
foo:
  - vitamin D
bar: much text
```

Essentially, how to "edit" `yaml` file before `parsing`.
